stringField: "hello"
intField: 123
boolField: true

stringArrayField:
  - "Hello"
  - "My"
  - "Name"
  - "Is"
  - John

intArrayField:
  - 1
  - 4
  - 5
  - 10

object:
  stringField: "hello1"
  intField: 1231
  boolField: false
  
objectArray:
  - stringField: "hello1"
    intField: 1231
    boolField: false
  - stringField: "hello2"
    intField: 1232
    boolField: true